- Example/Clappr/ViewController.swift
- Example/Tests/ContainerFactoryTests.swift
- Example/Tests/ContainerTests.swift
- Example/Tests/CoreFactoryTests.swift
- Example/Tests/CoreTests.swift
- Example/Tests/MediaControlTests.swift
- Example/Tests/PlaybackTests.swift
- Example/Tests/PlayerTests.swift
- Example/Tests/PosterPluginTests.swift
- Pod/Classes/Base/Core.swift
- Pod/Classes/Base/Options.swift
- Pod/Classes/Base/Playback.swift
- Pod/Classes/Base/Player.swift
- Pod/Classes/Factory/ContainerFactory.swift
- Pod/Classes/Factory/CoreFactory.swift
- Pod/Classes/Plugin/Container/PosterPlugin.swift
- Pod/Classes/Plugin/Playback/AVFoundationPlayback.swift
- README.md
This PR removes 'source url' parameters from player/core/container/playback and add it in options.
> Refactor: Send source on options

- Example/Tests/ContainerFactoryTests.swift
- Example/Tests/CoreFactoryTests.swift
- Example/Tests/CoreTests.swift
- Example/Tests/PlaybackTests.swift
- Example/Tests/PlayerTests.swift
- Example/Tests/PosterPluginTests.swift
- Pod/Classes/Base/Core.swift
- Pod/Classes/Base/Playback.swift
- Pod/Classes/Factory/ContainerFactory.swift
- Pod/Classes/Plugin/Playback/AVFoundationPlayback.swift
Currently multiple containers weren't used for anything.
> Refactor: Remove multiple containers structure

- Pod/Classes/Base/Core.swift
- Pod/Classes/Base/Loader.swift
- Pod/Classes/Base/MediaControl.swift
Allow media control replacement.
> Refactor: Make mediaControl more extensible

- Example/Tests/MediaControlTests.swift
- Pod/Classes/Base/MediaControl.swift
- Pod/Resources/MediaControlView.xib
Changed MediaControl elements to explicit optionals, so we can safely ignore missing elements when loading custom XIBs.
> MediaControl extensibility improvements

- Pod/Classes/Base/Container.swift
- Pod/Classes/Base/MediaControl.swift
- Pod/Classes/Base/Playback.swift
- Pod/Classes/Enum/ContainerEvent.swift
- Pod/Classes/Plugin/Playback/AVFoundationPlayback.swift
Changed track selection and available tracks to properties. There are also some minor improvements to media control timers and a new event indicating that a video source has changed.
> Track selection improvements

- Example/Tests/PlaybackTests.swift
- Pod/Classes/Base/Container.swift
- Pod/Classes/Base/MediaControl.swift
- Pod/Classes/Base/Playback.swift
- Pod/Classes/Base/Player.swift
- Pod/Classes/Plugin/Playback/AVFoundationPlayback.swift
> Expose seek method

- Pod/Classes/Base/AudioSource.swift
- Pod/Classes/Base/Playback.swift
- Pod/Classes/Base/Subtitle.swift
- Pod/Classes/Extension/AudioSourceExtension.swift
- Pod/Classes/Extension/SubtitleExtension.swift
- Pod/Classes/Plugin/Playback/AVFoundationPlayback.swift
Clappr should not use models from AVFoundation.
Closes #72
> Add subtitle and audio source abstractions

- Example/Tests/ContainerTests.swift
- Example/Tests/MediaControlTests.swift
- Example/Tests/PlaybackTests.swift
- Pod/Classes/Base/Container.swift
- Pod/Classes/Base/Core.swift
- Pod/Classes/Base/MediaControl.swift
- Pod/Classes/Base/Playback.swift
- Pod/Classes/Base/Player.swift
- Pod/Classes/Plugin/Playback/AVFoundationPlayback.swift
Also refactors most core/container/playback states to properties. (Closes #77)
> Add player state properties to public API

- Example/Clappr/ViewController.swift
- Pod/Classes/Base/Core.swift
- Pod/Classes/Base/Player.swift
- Pod/Classes/Enum/ClapprEvent.swift
- Pod/Classes/Enum/CoreEvent.swift
Implemented public enter/exit fullscreen events on core/player objects. Closes #80.
> Fullscreen events

- Example/Podfile.lock
- Example/Tests/PlaybackTests.swift
- Pod/Classes/Base/Playback.swift
> Playback: Seek when ready event is sent

- Clappr.xcodeproj/project.pbxproj
- Clappr/Classes/Base/BaseObject.swift
- Clappr/Classes/Base/Container.swift
- Clappr/Classes/Base/Core.swift
- Clappr/Classes/Base/Loader.swift
- Clappr/Classes/Base/Playback.swift
- Clappr/Classes/Base/Player.swift
- Clappr/Classes/Base/UIBaseObject.swift
- Clappr/Classes/Log/LogLevel.swift
- Clappr/Classes/Log/Logger.swift
- Clappr/Classes/Plugin/Container/LoadingContainerPlugin.swift
- Clappr/Classes/Plugin/Container/PosterPlugin.swift
- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Add a logger with levels:
- Debug
- Info
- Warning
- Error
- Off
This PR also log the main events on Clappr, such as events triggered and base objects creation.
> Add Logger

- Clappr/Classes/Extension/UIViewExtension.swift
- Clappr/Classes/Plugin/Container/PosterPlugin.swift
- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
> Revert "Fix playback issue related to buffering events"

- Clappr/Classes/Base/Container.swift
- Clappr/Classes/Base/Options.swift
- Clappr/Classes/Base/Playback.swift
- Example/ViewController.swift
- Tests/ContainerTests.swift
- Tests/PlaybackTests.swift
- Tests/PosterPluginTests.swift
This change prevents AnyObject forced cast
> Remove AnyObject forced cast

- Clappr.podspec
- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Fix the bug created by the #111 PR
> Multiple onReady are being sent

- Clappr.xcodeproj/project.pbxproj
- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Example/Info.plist
- Example/ViewController.swift
- README.md
Changes to enable the external playback keep running on background
> Enable Background Playback

- Clappr/Classes/Base/Container.swift
- Clappr/Classes/Base/Core.swift
- Clappr/Classes/Base/Player.swift
- Clappr/Classes/Plugin/Container/LoadingContainerPlugin.swift
- Clappr/Classes/Plugin/Container/PosterPlugin.swift
- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
* Improve event flow
* Fix PosterPlugin to not display media control initially
> Refactoring clappr

- Clappr/Classes/Base/BaseObject.swift
- Clappr/Classes/Base/Container.swift
- Clappr/Classes/Base/Core.swift
- Clappr/Classes/Base/MediaControl.swift
- Clappr/Classes/Base/Playback.swift
- Clappr/Classes/Base/Player.swift
- Clappr/Classes/Base/UIBaseObject.swift
- Clappr/Classes/Enum/InternalEvent.swift
- Clappr/Classes/Plugin/Container/LoadingContainerPlugin.swift
- Clappr/Classes/Plugin/Container/PosterPlugin.swift
- Clappr/Classes/Plugin/Container/UIContainerPlugin.swift
- Clappr/Classes/Plugin/Core/UICorePlugin.swift
- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Clappr/Classes/Plugin/Playback/NoOpPlayback.swift
- Clappr/Classes/Protocol/Plugin.swift
- Tests/CoreTests.swift
* Add destroy method for playback, plugins, container, core, media control and player.
> Implement destroy logic

- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
> Change AVPlayer visibility to dynamic private

- Clappr.xcodeproj/project.pbxproj
- Example/Base.lproj/Main.storyboard
- Example/ViewController.swift
With this new initial view controller, we can test, and exemplify the
use of `player.destroy()`
> Create an initial view controller

- Clappr.xcodeproj/project.pbxproj
- Clappr/Classes/Helper/AppStateManager.swift
- Tests/AppStateManagerTests.swift
- Add AppStateManager thats handles with App States(background and foreground)
> chore: add appStateManager thats handle with app states

- .travis.yml
- Cartfile.private
- Cartfile.resolved
- Clappr.xcodeproj/project.pbxproj
- Clappr/Classes/Base/BaseObject.swift
- Clappr/Classes/Base/EventDispatcher.swift
- Clappr/Classes/Base/Player.swift
- Clappr/Classes/Base/UIBaseObject.swift
- Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Clappr/Classes/Protocol/EventProtocol.swift
- Tests/BaseObjectTests.swift
- Tests/EventDispatcherTests.swift
Refactor BaseObject to be able to change the architecture.
Run all tests.
> Refactor BaseObject

- Clappr.xcodeproj/project.pbxproj
- Clappr/Classes/Base/UIObject.swift
- Clappr/Classes/Plugin/UIPlugin.swift
- Tests/UIPluginTests.swift
As we're evolving our architecture our first step is to make `UIPlugin` conforming to `UIObject`, having a `View?` and a `render()` method
Makes sure all tests pass.
> UIPlugin now conforms with UIObject

- Clappr/Classes/Base/BaseObject.swift
> Set BaseObject as Public

- Clappr.podspec
Adjust Clappr to be published in Cocoapods(iOS and tvOS) with the same Podspec.
Just run `pod lib lint` and check if everything is working
> Update PodSpec to support tvOS and iOS

- Sources/Clappr/Classes/Base/Container.swift
Expose container options to be able to change it out of the class.
> Expose container options

- Tests/Clappr_UITests/FullscreenUITests.swift
The UI tests in dev branch were broken.
Set the UI tests to use async approach.
Run the UI tests and check if everything is ok.
> Set the ui tests to use async approach

- Tests/Clappr_UITests/FullscreenUITests.swift
The flakiness of this fullscreen test is blocking the release.
> This test will be removed at the moment, but the flakiness problem should be fixed.
1. Run all UI tests
> Remove flaky test

- .gitignore
- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Loader.swift
- Sources/Clappr/Classes/Plugin/Container/SpinnerPlugin.swift
- Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Sources/Clappr_tvOS/Classes/Plugin/Playback/AVFoundationPlayback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/SpinnerPluginTests.swift
- Tests/Clappr_UITests/Extension/XCUIApplicationExtension.swift
- Tests/Clappr_UITests/PlaybackTests.swift
- Tests/Clappr_UITests/XCTWaiter+WaitFor.swift
- fastlane/Fastfile
- Set accessibility identifier of `AVFoundationPlayback` to identify when a video is playing in UI tests;
- Rename `LoadingContainerPlugin` to `SpinnerPlugin` to follow plugin name pattern;
- Hide `SpinnerPlugin` view instead of only make spinning wheel disappear;
- Increase test coverage of `SpinnerPlugin`;
- Run unit tests before UI tests properly;
- Change order of execution of the tests;
Run all tests.
> Quality Assurance Improvement

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/MediaOption.swift
- Tests/Clappr_Tests/MediaOptionTests.swift
Expose `MediaOption` to be able to test out of the module properly.
Run all tests.
> Expose MediaOption constructor for testing purposes

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Extension/AVFoundationPlayback+ViewPort.swift
- Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Sources/Clappr_tvOS/Classes/Plugin/Playback/AVFoundationPlayback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
- Tests/Clappr_Tests/AVFoundationPlaybackViewPortTests.swift
- Tests/Clappr_Tests/AVPlayerItemMock.swift
- Tests/Clappr_Tests/AVPlayerStub.swift
- Tests/Clappr_tvOS_Tests/AVFoundationPlaybackTests.swift
Setup the video maximum quality according to the viewport in iOS and tvOS
1. Run all unit tests
> Setup viewport in AVFoundationPlayback

- Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
Allow observing the player with kvo.
Run all tests.
> Setup dynamic property in player

- Sources/Clappr_tvOS/Classes/Base/Playback.swift
To apply dvr playback changes on tvOS schema
ps: once we won't merge both playback right now, it would be better to not increase diff
> Add dvr properties on tvos playback

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Container.swift
- Sources/Clappr/Classes/Base/SharedData.swift
- Tests/Clappr_Tests/ContainerTests.swift
Create a share structure on container that all plugins can store and retrieve data
* Run tests
* Use sharedData in 2 different plugins
> Create a way to share data between plugins

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/AvailableMediaOptions.swift
- Sources/Clappr/Classes/Base/Playback.swift
- Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Sources/Clappr_tvOS/Classes/Plugin/Playback/AVFoundationPlayback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
To trigger audioAvailable and subtitleAvailable events informing if has default value
Run tests
> Adjust audio and subtitle default selection

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Core.swift
- Sources/Clappr/Classes/Base/Options.swift
- Sources/Clappr/Classes/Extension/UIImage+Ext.swift
- Sources/Clappr/Classes/Extension/UIView+Ext.swift
- Sources/Clappr/Classes/Plugin/Core/MediaControl/FullscreenButton.swift
- Sources/Clappr_iOS/Classes/Base/FullScreen/FullScreenStateHandler.swift
- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift
- Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/FullscreenButtonTests.swift
- Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift
⚠️ DO NOT MERGE THIS PR UNTIL [THIS PR](https://github.com/clappr/clappr-ios/pull/227) IS MERGED ⚠️
Creating a Fullscreen plugin to append in MediaControl plugins
Run example and tests: 
1. Make sure that Fullscreen functionality conform to business rules
2. Make sure to test Fullscreen controlled by app and by player
3. Make sure to test entering in Fullscreen mode
> Create Fullscreen plugin

- Sources/Clappr_iOS/Classes/Base/Player.swift
- Sources/Clappr_tvOS/Classes/Base/Player.swift
- Tests/Clappr_tvOS_Tests/PlayerTests.swift
Fix tvOS playback.
Run tvOS example and check if video is played properly.
> Fix tvOS playback

- Sources/Clappr/Classes/Base/Loader.swift
> Remove obsolete log message

- README.md
Improve docs with the implementation of `MediaControl` by panels.
> Docs: Media Control

- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/TimeIndicator.swift
To expose TimeIndicator margin properties
> Expose TimeIndicator margin properties

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Container.swift
- Sources/Clappr/Classes/Base/Core.swift
- Sources/Clappr/Classes/Base/Factories/ContainerFactory.swift
- Sources/Clappr/Classes/Base/Factories/CoreFactory.swift
- Sources/Clappr/Classes/Base/Loader.swift
- Sources/Clappr/Classes/Extension/Array+appendOrReplace.swift
- Sources/Clappr/Classes/Factory/PlaybackFactory.swift
- Sources/Clappr_iOS/Classes/Base/Player.swift
- Sources/Clappr_tvOS/Classes/Base/Player.swift
- Tests/Clappr_Tests/AVFoundationPlaybackStateMachineEventsTests.swift
- Tests/Clappr_Tests/Classes/Extensions/Array+appendOrReplaceTests.swift
- Tests/Clappr_Tests/ContainerTests.swift
- Tests/Clappr_Tests/CoreTests.swift
- Tests/Clappr_Tests/LoaderTests.swift
- Tests/Clappr_Tests/PlaybackFactoryTests.swift
- Tests/Clappr_Tests/PlayerTests.swift
- Tests/Clappr_Tests/PosterPluginTests.swift
- Tests/Clappr_tvOS_Tests/PlayerTests.swift
- Tests/Extensions/Loader+Plugins.swift
Refactor to improve *Clappr's Architecture* scalability to test new Playbacks. Where we:
* Changed the way how we instantiate a `Core` and `Container` in `Player`.
* Changed the playbacks that exist in Loader from `[Plugin.Type]` to `[Playback.Type]`
- Run all tests
- Check if the video loads properly
- Use `configure` to reload a video
- Use `load` to reload a video
> Create Core and Container Factories

- Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/Layout/MediaControlViewTests.swift
> Fix media control view tests

- Sources/Clappr/Classes/Enum/Event.swift
- Sources/Clappr/Classes/Enum/InternalEvent.swift
Add namespace on event's name to avoid collision on notificationCenter
- application must have the same behaviour
- run tests
> Avoid event collision

- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/FullscreenButton.swift
- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift
- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Seekbar/Views/SeekbarView.swift
The goal is to protect some properties and methods from external access.
1 - Run the tests and make sure that they pass
> Protect plugins methods and properties

- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
Change when `didUpdateDuration` to be able to see total duration of offline videos.
Run `make test`.
> Change when didUpdateDuration is triggered

- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Reverts clappr/clappr-ios#297. We will include these changes after external testing.
> Revert "Fix UI Freezing"

- Sources/Clappr/Classes/Extension/AVAsset+Ext.swift
- Sources/Clappr/Classes/Extension/Dictionary+Ext.swift
- Sources/Clappr/Classes/Extension/UIImageView+Ext.swift
- Sources/Clappr/Classes/Helper/AVURLAssetWithCookiesBuilder.swift
- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Sources/Clappr_iOS/Classes/Animation/SeekBubble/SeekBubble.swift
- Sources/Clappr_iOS/Classes/Base/Player.swift
- Sources/Clappr_iOS/Classes/Plugin/Container/PosterPlugin.swift
- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Seekbar/Views/SeekbarView.swift
- Sources/Clappr_tvOS/Classes/Base/Player.swift
Remove warnings pointed by `lint`.
- Run all test
- Run iOS and tvOS samples
> Remove warnings

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Core.swift
- Sources/Clappr/Classes/Helper/Environment.swift
Adds an `Environment` attribute to `Core` in order to store `playerId`
> Environment core attribute

- Example/Clappr_tvOS/ViewController.swift
- Sources/Clappr/Classes/Base/MediaOption.swift
- Sources/Clappr/Classes/Factory/MediaOptionFactory.swift
- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Sources/Clappr_tvOS/Classes/Plugin/Playback/AVFoundationPlayback/AVFoundationPlayback+tvOS.swift
Fix a problem in tvOS where the user cannot turn subtitles off after choosing a language.
Check manually, I've already changed the example tvos video for a bip-bop with subtitles!
> Select off subtitles

- Sources/Clappr_iOS/Classes/Base/Player.swift
- Sources/Clappr_tvOS/Classes/Base/Player.swift
Make init method and public interface  from `Player` available when importing in objective-c
> Make player available in objective c

- Sources/Clappr/Classes/Enum/Event.swift
- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Sources/Clappr_iOS/Classes/Base/Player.swift
- Sources/Clappr_tvOS/Classes/Base/Player.swift
- Tests/Clappr_Tests/AVFoundationPlaybackStateMachineEventsTests.swift
- Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
- Tests/Clappr_Tests/PlayerTests.swift
- Tests/Clappr_tvOS_Tests/PlayerTests.swift
Create `didUpdateBitrate`event.
1. Add those lines to `ViewController` inside method `listenToPlayerEvents`:
```swift
player.on(Event.didUpdateBitrate) { userInfo in print("on didUpdateBitrate with: \(userInfo?["bitrate"])") }
```
2. Run sample app and check if the message is printed.
> Create didUpdateBitrate event

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Core.swift
- Sources/Clappr/Classes/Enum/Event.swift
- Sources/Clappr/Classes/Plugin/Core/OverlayPlugin.swift
- Sources/Clappr/Classes/Plugin/Core/SimpleCorePlugin.swift
- Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/DrawerPlugin.swift
- Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Core/Drawer/DrawerPluginTests.swift
- To introduce a base class for creating drawer plugins (plugins that will be placed at the edges of the player, like floating panels)
- We haven't added the possible drawer positions yet as they might be added as we develop the drawers. Therefore, the only position available for now is `undefined`
- Run the test suite and nothing should break
- You can create a drawer plugin to test out the behaviors:
```swift
// Add this plugin to the built in plugins list!
class MyDrawer: DrawerPlugin {
override class var name: String {
return "MyDrawer"
}
override var position: DrawerPlugin.Position {
return .undefined
}
override var size: CGSize {
return CGSize(width: 200, height: 100)
}
let toggleButton = UIButton(frame: CGRect(origin: .zero, size: CGSize(width: 200, height: 100)))
override func …
```
> DrawerPlugin

- Cartfile.private
- Cartfile.resolved
- Clappr.xcodeproj/project.pbxproj
- To bump the project's swift version to 5.0
- run `make test` and nothing should break
> Bump swift version to 5

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Extension/AVPlayerItem+Ext.swift
- Sources/Clappr/Classes/Extension/TimeInterval+Extensions.swift
- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/Classes/Extensions/AVPlayerItemExtensionTests.swift
- Tests/Clappr_Tests/Classes/Extensions/TimeIntervalExtensionTests.swift
To solve some of the minor Code Climate issues we have in this file.
We know that AVFoundationPlayback needs a deeper refactoring strategy, so this pull request is aiming to help us out in the future and not to solve the root of the problem.
- Since this is just some refactoring, run the tests and nothing should break.
- You can even try out some backward/forward seek since there were some changes around this code.
> AVFoundationPlayback code climate issues fix

- fastlane/Fastfile
Set `Apple TV 4K` and `iPhone 8` as a device list on test lane.
> Adjust device list on test lane

- fastlane/Fastfile
#Goal 
Uncomment steps on release lane.
> [Fix] Fastfile script

- Tests/Clappr_Tests/Classes/Plugin/Container/ContainerTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Core/Drawer/BottomDrawerPluginTests.swift
Correct the broken tests on `ContainerTests` and  `BottomDrawerPluginTests`
1. Run test suit
2. Check if all tests passed
> Correct the broken unit tests

- Example/Clappr/Base.lproj/Main.storyboard
- Example/Clappr/ViewController.swift
- Sources/Clappr_iOS/Classes/Animation/QuickSeekAnimation.swift
- Sources/Clappr_iOS/Classes/Animation/SeekBubble/SeekBubble.swift
- Sources/Clappr_iOS/Classes/Plugin/Base/QuickSeekPlugin.swift
Goal
---
Remove memory leaks to avoid the app being slow or crashing.
How to Test
---
1. Run the Clappr Example
1. Proceed to the PlayerViewController
1. Tap the `Recreate Player` button multiple times
1. Click on the `Debug Memory Graph` button in the bottom Debug Area of Xcode.
1. Click the `Show only content from workspace` button to filter the list.
1. Check if there's any class from Clappr in the memory leak list.
> Remove memory leaks

- Sources/Clappr_iOS/Classes/Base/Player.swift
- Sources/Clappr_tvOS/Classes/Base/Player.swift
Goal
---
Create a separate callback for the error event.
How to test
---
- Run test suite for both iOS and tvOS targets
> Create a unique callback to handle error user info

- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/Classes/Mocks/PlayerItemMock.swift
- Tests/Clappr_Tests/Classes/Mocks/PlayerMock.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackQualityMetricsTests.swift
Creating and exposing new quality metrics from `AVFoundationPlayback`. 
- Run test suite.
> New quality metrics

- Sources/Clappr_tvOS/Classes/Base/Player.swift
Fix the focus for the elements in tvOS.
Run the test suite.
> Fix focus from elements in tvos

- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/PlayButton.swift
- Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/PlayButtonTests.swift
> Refactor PlayButton

- Sources/Clappr/Classes/Plugin/Container/SpinnerPlugin.swift
- Tests/Clappr_Tests/Classes/Plugin/Container/SpinnerPluginTests.swift
- Add `didPause` and `didStop` events on `SpinnerPlugin` to stop animating.
- Add `willPlay` events on `SpinnerPlugin` to start animating.
> SpinnerPlugin pause/stop events

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Enum/Event.swift
- Sources/Clappr/Classes/Plugin/Core/UICorePlugin.swift
- Sources/Clappr_tvOS/Classes/Base/Player.swift
- Sources/Clappr_tvOS/Classes/Extension/UIFocusEnvironment+Ext.swift
- Sources/Clappr_tvOS/Classes/Extension/UIFocusEnvironment+ext.swift
- Tests/Clappr_Tests/Classes/Extensions/UIFocusEnvironment+ExtTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Core/UICorePluginTests.swift
- Tests/Clappr_tvOS_Tests/PlayerTests.swift
Introduce the possibility of a visual entity to request/release focus on `tvOS`
Run tests
> Focus update event

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Core.swift
- Sources/Clappr_iOS/Classes/Base/Layers/BackgroundLayer.swift
- Sources/Clappr_iOS/Classes/Base/Layers/LayersCompositor.swift
- Sources/Clappr_iOS/Classes/Base/LayersComposer.swift
- Tests/Clappr_Tests/Classes/Base/BackgroundLayerTests.swift
- Tests/Clappr_Tests/Classes/Base/LayersCompositorTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift
Create the new layers structure and add the Background Layer to it.
1. Run the Clappr example app
2. Open the View Hierarchy Debugger
3. Check if views follow the image below:
> Add Background Layer

- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift
- Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/PlayButton.swift
Changes the access of some methods of the PlayButton and MediaControl class, from private to public.
> Changes the access type for some PlayButton/MediaControl events

- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
- Fix `AVFoundationPlaybackTests` for local assets
> Fix AVFoundationPlaybackTests

- Clappr.xcodeproj/project.pbxproj
- Sources/Clappr/Classes/Base/Core.swift
- Sources/Clappr/Classes/Base/Layers/CoreLayer.swift
- Sources/Clappr/Classes/Base/Layers/LayerComposer.swift
- Tests/Clappr_Tests/Classes/Base/Layers/CoreLayerTests.swift
- Tests/Clappr_Tests/Classes/Base/Layers/LayerComposerTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift
- Tests/Clappr_Tests/Classes/Stubs/UICorePluginStub.swift
Continue the implementation of the visual layers abstraction by adding Core layer.
1. Add the following snippet to LayerComposer.swift#20
```swift
coreLayer.backgroundColor = .yellow
```
2. Run the Clappr_Example project
3. Enable view hierarchy debugger
4. You should be able to see the new layer
> Create Core layer

- Sources/Clappr/Classes/Extension/AVFoundationPlayback+DVR.swift
- Sources/Clappr/Classes/Extension/AVFoundationPlayback+ViewPort.swift
- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackMediaSelectionTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackQualityMetricsTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackStopActionTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackSubtitleTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
- Tests/Clappr_UITests/PlaybackTests.swift
Move AVPlayer creation to AVFoundationPlayback initialization.
1 . Run all automated tests
> Create AVPlayer during AVFoundationPlayback's initialisation

- Clappr.xcodeproj/project.pbxproj
- Tests/Clappr_UITests/Dashboard/DashboardViewElements.swift
- Tests/Clappr_UITests/Dashboard/DashboardViewInteractor.swift
- Tests/Clappr_UITests/Extension/XCUIApplicationExtension.swift
Adjust ui test and build for tvOS on Xcode 12  
1 . Run all automated tests
> Removed unused ui tests for fullscreen

- Clappr.xcodeproj/project.pbxproj
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVPlayerItemInfoTests.swift
- Tests/Clappr_Tests/Classes/Stubs/AVPlayerItemStub.swift
- Tests/Clappr_tvOS_Tests/AVFoundationNowPlayingTests.swift
> Fix Test on AVFoundation Playback for tvOS

- Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
Change moment to seek when liveStartAtTime has a value.
1. Run unit tests
> Change moment to seek when liveStartAtTime has a value

- README.md
Mark repo is no longer supported.
> Mark repo is no longer supported
