clappr/clappr-ios

Example/Podfile.lock, Example/Tests/BaseObjectTests.swift, Pod/Classes/Base/BaseObject.swift, Pod/Classes/Base/UIBaseObject.swift, Pod/Classes/Protocol/EventProtocol.swift
Why? 
- Avoid using callback memory address for identifying event.
=> BaseObject: Add eventKey for handling on/off events

Clappr/Classes/Base/MediaOption.swift, Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
MediaOption is now Equatable, and the default subtitle option is `offSubtitle` instead of `nil`.
=> MediaOption improvements

Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
This PR fixes an issue where the playback was triggering .Ready events after seeking
=> Avoid sending unnecessary ready events

Cartfile.resolved, Clappr/Classes/Base/Container.swift, Tests/ContainerTests.swift
When the user is trying to load a new resource, the previous playback was not removed from the container's view, causing the player to keep showing the last video's frame, while the new video is being played on background.
=> Remove previous Playback from view

Clappr/Classes/Base/MediaControl.swift
**Goal**
A problem was happening when the player was inside a scrollview, the conflict was happening between the swipe and scroll events.
We intend to change the MediaControl slide bar for a native component.
**How to test**
To simulate the problem, open the sample and put the player inside a ScrollView.
=> Fix player slider swipe when inside a ScrollView

Clappr/Classes/Base/FullscreenController.swift
The problem is that when the app calls the function setFullscreen, the default was only landscapeRight.
To fix that we changed the property inside FullscreenController to get the device orientation. 
Open the clappr sample and put a breakpoint at the line **100** in `Core.swift`.
Run the app, and change the device orientation, when the breakpoint stops check the value of `fullscreenController.preferredInterfaceOrientationForPresentation.rawvalue`
The value should be 3 for `landscapeLeft` and 4 for `landscapeRight`, you can see more here:
https://developer.apple.com/documentation/uikit/uiinterfaceorientation
=> Fix fullscreen orientation according to the device orientation

README.md
The current documentation ([wiki](https://github.com/clappr/clappr-ios/wiki) and [readme](https://github.com/clappr/clappr-ios/blob/dev/README.md)) has some duplications and bad design. 
The goal is remove duplication between readme and wiki and reorganize the informations to be more clean and maintainable.
Read  [wiki](https://github.com/clappr/clappr-ios/wiki) and [readme](https://github.com/clappr/clappr-ios/blob/dev/README.md).
=> Update and reuse documentation

Clappr/Classes/Base/Core.swift, Clappr/Classes/Base/FullScreenStateHandler.swift, Clappr_UITests/FullscreenUITests.swift, Example/ViewController.swift, Tests/CoreTests.swift
After the fullscreen controled by app was added, the method ``setFullscreen`` doesnt set player to fullscreen when **kFullscreenByApp is false**.
1) Open Sample
2) Disable **Fullscreen controled by app** and **Start player as Fullscreen**
3) Tap on **start video**
4) Change orientation of App to landscapeLeft
**obs: Make sure that the player was set to fullscreen when orientation changes**
=> Fix setFullscreen when the fullsscreen is controled by player

Clappr.xcodeproj/project.pbxproj, Clappr/Classes/Plugin/Container/PosterPlugin.swift, Clappr/Classes/Plugin/Playback/NoOpPlayback.swift, Tests/NoOpPlaybackTests.swift, Tests/PosterPluginTests.swift
- Remove trigger ready event on render of NoOpPlayback. 
- Handle visibility of PosterPlugin by listening the didChangePlayback event.
When the source of the video isn't a valid source(mp4, hls, etc...), the activePlayback is setted to NoOpPlayback.
When a ready event is trigger by the activePlayback, the PosterPlugin handles their own visibility.
1) Set ``kSourceUrl`` value to **"invalid"** on ``DashboardViewController.swift``
2) Add a breakpoint on ``Event.ready`` at ``ViewController.swift``
3) Ready event should'nt be triggered
=> NoOpPlayback should'nt trigger a ready event on render

Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Was reported that the player was sending a ready event twice. We notice that NoOpPlayback was triggering a ready event in render method, so we decided to no trigger anymore. 
Was reported that the ready event is triggered after the willPlayAd. Following the desired architecture of player, the ready event must be triggered after the idle state.
1. Run all unit/ui tests
2. On logs, Check out if the ready event was triggered before willPlayAd
=> Send a ready event before the video starts to play

.gitignore, Clappr.xcodeproj/xcshareddata/xcschemes/Clappr_tvOS.xcscheme, fastlane/Fastfile
Adjust fastlane script to works for iOS and tvOS.
1. `make setup` and `make test`: makes sure that all the tests pass
**This is just an explanation of how the release will work. You should not try this unless you're really publishing a new Clappr version.**
If you want to test the script without publishing, you need to do the following
1. Fork and clone this repo your machine;
2. Comment the `pod_push` command in the script;
3. Run `make setup` and `make test`;
4. Run `pod lib lint` to check it the podspec is valid to publish;
5. Change the path to your forked repo in the script:
```
set_github_release(
repository_name: "your_github_username_here/clappr-ios",
api_token: ENV["GITHUB_TOKEN"],
name: "",
tag_name: options[:version],
description: "TODO: write release notes here"
)
```
6. In …
=> Adjust fastlane for ios tvos release

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr_tvOS/Classes/Base/Core.swift, Tests/Clappr_Tests/CoreTests.swift
We have identified that the Container and Core views were not in the right order, as specified in [our documentation](https://github.com/clappr/clappr-docs/wiki/Architecture).
As you can see, the first layer should be Core and the Container is right behind it. In the current implementation, is the opposite.
1. Make sure that all tests are passing;
2. Run Clappr and check if everything behaves correctly
=> Change the order of how Container and Core views are rendered

Clappr.xcodeproj/xcshareddata/xcschemes/Clappr.xcscheme
Enable test coverage in xcode.
Run tests in xcode and check coverage report.
=> Enable test coverage for Clappr schema

Example/Clappr/Base.lproj/Main.storyboard, Example/Clappr/ViewController.swift, Tests/Clappr_UITests/FullscreenUITests.swift
Remove rotation logic of portrait/landscape of Clappr Example in order to simplify the sample app.
Add a ViewController in the sample app to be used when kFullscreenByApp option is enabled.
1. Open the sample app.
2. Enable fullscreen controlled by the app.
3. Check if the player enters in the fullscreen mode when the fullscreen button is tapped.
4. Taps again and check if it goes to embed mode.
=> Add Fullscreen ViewController on Sample App

Cartfile.private, Cartfile.resolved, Clappr.xcodeproj/project.pbxproj, Example/Clappr/ViewController.swift, Example/Clappr_tvOS/ViewController.swift, Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Sources/Clappr_tvOS/Classes/Plugin/Playback/AVFoundationPlayback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Clappr_tvOS_Tests/AVFoundationPlaybackTests.swift
To create two new events:
- willSeek: triggered when user wants to play another part of the video;
- didSeek: triggered when playback will start another part of the video;
**seek event will be deprecated**
In iOS and tvOS: 
1. Open any vod;
2. Move scrubber to any point of the video;
3. Check the output if willSeek and didSeek events were triggered;
After merge, update clappr wiki with the new events.
=> Create willSeek and didSeek events

Sources/Clappr_iOS/Classes/Extension/AVURLAssetWithCookiesBuilder.swift, Tests/Clappr_Tests/AVURLAssetWithCookiesTests.swift
When we get cookies with different paths, we are not able to retrieve them all from HTTPCookieStorage
Change the way we fetch it
=> Retrieve all stored cookies

Sources/Clappr/Classes/Enum/InternalEvent.swift, Sources/Clappr_iOS/Classes/Base/Playback.swift, Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift
Fix startAt when the player is ready. 
1. Run all unit tests.
2. Try to use startAt in iOS 10.3 and iOS 11.
=> Fix start At for iOS < 11

Sources/Clappr_iOS/Classes/Base/MediaControl.swift
Hold AirPlay Button instance in MediaControl
Marking the AirPlay Button Outlet as `weak` was making the MediaControl to loose the button's reference when used in iOS 11.3 beta 4 (Xcode 9.3 beta 4)
- Build Clappr_Example and test the AirPlay feature 
- Is desirable that you run this test in both:
(1) Xcode 9.3 Beta 4 - iOS 11.3 beta 4
(2) Xcode 9.2 - iOS 11.2
=> fix: hold AirPlay Button instance in MediaControl

Clappr.xcodeproj/project.pbxproj, Sources/Clappr_iOS/Classes/Base/FullScreen/FullscreenController.swift, Tests/Clappr_Tests/FullscreenTests.swift
Hide the Home Button for iPhone X when in Fullscreen mode
- Open an iPhone X
- Turn off properties of `Fullscreen controlled by app` and `enter Fullscreen mode`
- Play the Video on Portrait mode
- Press Fullscreen button, after a second you will notice that the home button is hidden automatically with the media control
=> Auto Hide Home Button on fullscreen mode

Sources/Clappr/Classes/View/DragDetectorView.swift, Sources/Clappr_iOS/Classes/Base/Core.swift, Sources/Clappr_iOS/Classes/Base/FullScreen/FullScreenStateHandler.swift, Tests/Clappr_Tests/CoreTests.swift
When we tried to call the method `destroy()` from a player instance we had memory issues with  `Core`, `FullscreenStateHandler` and `DragDetectorView` that were not deallocated.
Before:
After:
Download the [patch](https://gist.github.com/nabilsafatli/cc492a6ba4fe4b65358b51f7ef9d8f9d), and apply it by running the command `git apply {patch file}`
With this [patch](https://gist.github.com/nabilsafatli/cc492a6ba4fe4b65358b51f7ef9d8f9d), you will be able to open Clappr sample, disable the option of `enter fullscreen` and play the video many times creating new instances with the button to make sure that everything is being deallocated.
=> Destroy player

Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Enum/InternalEvent.swift, Sources/Clappr/Classes/Plugin/Core/DVRPlugin.swift, Tests/Clappr_Tests/AVPlayerItemStub.swift, Tests/Clappr_Tests/AVPlayerStub.swift, Tests/Clappr_Tests/DVRPluginTests.swift
Implement two events to make sure that DVR works in the player and other plugins have what they need of information to change when necessary
- `supportDVR` The current live media being played, supports DVR
- `usingDVR` The current live media being played is using the DVR ( it means that the scrubber is not in the end of the scrubber)
=> DVR Integration and Events

Sources/Clappr_iOS/Classes/Base/Playback.swift, Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Clappr_Tests/AVPlayerItemStub.swift
Adds a property that returns the position inside a DVR window. Let's say we have a window of 60 seconds, starting at the second 120 and ending in 180.
If the position is `150` the `dvrPosition` should return `30` (a value between `0` and the duration of the window)
=> Adds a property to return the position inside a DVR window

Sources/Clappr_iOS/Classes/Base/Options.swift, Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
Enable minDvrTime be set by options
1 - In Example app set the option[kMinDvrOption] to 15
2 - Run the app and check if is possible make a seek in a Live video
3 - Run all tests
=> Add DVR minimum size to Options

fastlane/Fastfile
Allow coocoapods publication when the framework has warnings.
=> Fix pod push in fastlane script to allow warnings

Sources/Clappr_iOS/Classes/Base/Playback.swift, Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift, Sources/Clappr_tvOS/Classes/Base/Playback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Clappr_Tests/AVPlayerItemStub.swift
To get the thumbseek image for a live video with dvr, it is necessary to obtain the date of the media. So, we need to expose a property informing the media current date. 
This property is loaded from master playlist tag `#EXT-X-PROGRAM-DATE-TIME`. 
Run `make test`.
=> Expose property to inform media current date

Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr_iOS/Classes/Base/Playback.swift, Sources/Clappr_iOS/Classes/Plugin/Playback/AVFoundationPlayback.swift, Sources/Clappr_tvOS/Classes/Base/Playback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Clappr_Tests/AVPlayerItemStub.swift
After talking with the Clappr team, some names were changed to inform better the DVR availability and status.
- Create an event to indicate the change of DVR availability - didChangeDvrAvailability
- Change the property `supportDvr` to `isDvrAvailable`
- Change the property `isUsingDvr` to `isDvrInUse`
- Change the event `usingDvr` to `didChangeDvrStatus`
- Create a method `seekToLivePosition()` to make possible for plugins to redirect a live playback to last live moment available
=> Refactoring DVR to keep Clappr architecture consistency

Sources/Clappr_iOS/Classes/Base/Playback.swift, Tests/Clappr_Tests/PlaybackTests.swift
Ignore startAt option in playback for live videos
Run `make test`.
=> Ignore startAt option in playback for live videos

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr_iOS/Classes/Base/FullScreen/FullScreenStateHandler.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Tests/Clappr_Tests/CoreTests.swift
In full screen state, core is placed in another view. Before player destruction, we need to place it in the previous view to not create a memory leak. 
`FullscreenStateHandler` was retaining `Core` avoiding its destruction.
Run `make test`.
=> Exit full screen when player is destroyed

Sources/Clappr/Classes/Base/MediaControl.swift, Tests/Clappr_Tests/MediaControlTests.swift
After the study to find duplicated triggered events at our code. We found some unnecessary events been throw by our MediaPlayer. To fix that and be sure that our users do not listen events from the wrong place, we decided to remove these unnecessary event triggers.
1. Run clappr tests
=> Remove unnecessary events rethrow

Clappr.xcodeproj/project.pbxproj, README.md, Sources/Clappr/Classes/Base/Container.swift, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Loader.swift, Sources/Clappr/Classes/Factory/PlaybackFactory.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Tests/Clappr_Tests/ContainerTests.swift, Tests/Clappr_Tests/CoreTests.swift, Tests/Clappr_Tests/LoaderTests.swift, Tests/Clappr_Tests/MediaControlTests.swift, Tests/Clappr_Tests/PlaybackFactoryTests.swift, Tests/Clappr_Tests/PlayerTests.swift, Tests/Clappr_Tests/PosterPluginTests.swift, Tests/Clappr_tvOS_Tests/PlayerTests.swift, Tests/Extensions/Loader+Plugins.swift
The objective is to change `Loaders` class responsibility in the architecture.
Instead of holding the `MediaControl` and `Options` reference, the `Loader` now is responsible for managing and holding plugins reference across the Player lifecycle.
[ ------- **Loader** ------- ]
| _containerPlugins_ 
| _corePlugins_
| _playbacks_ **changed the name from playbackPlugins to playback
| _mediaControl_ **removed
| _externalPlugins_
[---------------------------]
The `Loader` is now a Singleton and won't receive the external plugins and options in its constructor.
- Open the player and check if all controls are available correctly without any problem
- Run all tests and make sure they pass
=> Refactoring Loader

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Loader.swift, Sources/Clappr/Classes/Extension/Array+UniquePlugins.swift, Sources/Clappr/Classes/Extension/Array+appendOrReplace.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/TimeIndicator.swift, Tests/Clappr_Tests/Classes/Extensions/Array+appendOrReplaceTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/TimeIndicatorTests.swift, Tests/Clappr_Tests/CoreTests.swift, Tests/Extensions/Loader+Plugins.swift
To load `MediaControl` plugins through the `Loader`.
1. Open the example
2. Play the video
3. You should see fullscreen, time indicator and play/pause button plugins
4. Interact with them and make sure that their behavior is ok
=> Handle MediaControl plugins in Loader

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Enum/InternalEvent.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/PlayButton.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift
To trigger core events telling if the `MediaControl` will show or hide.
In any `CorePlugin` (like `PlayButton`) add the following code:
```swift
listenTo(core, eventName: Event.didShowMediaControl.rawValue) { _ in print("didShowMediaControl") }
listenTo(core, eventName: Event.didHideMediaControl.rawValue) { _ in print("didHideMediaControl") }
listenTo(core, eventName: Event.willHideMediaControl.rawValue) { _ in print("willHideMediaControl") }
listenTo(core, eventName: Event.willShowMediaControl.rawValue) { _ in print("willShowMediaControl") }
```
Then, play the video and manipulate `MediaControl` looking at the log output.
=> Trigger events when MediaControl is show/hidden

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Clappr_Tests/PlayerTests.swift
According to the following picture from [Clappr-docs](https://github.com/clappr/clappr-docs/wiki/Architecture), the player should follow some states when interacting with the playback:
With this PR we want to cover some scenarios of the state, our tests are:
- when player is ready to play ->  `currentState` must be `idle`
- when play is called -> changes `isPlaying` to *true*
- when pause is called -> changes `currentState` to paused, and `isPaused` to *true*
- when pause is called -> it changes `currentState` to paused, and `isPaused` to *true*
- when seek is called -> it changes `currentState` to playing, and `isPlaying` to *true*
- when stop is called -> it changes `currentState` to idle 
- when video is over -> it changes `currentState` to idle
- when is not likely to keep up -> it …
=> Add tests for the state of the Playback state machine

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Enum/Event.swift, Tests/Clappr_Tests/AVFoundationPlaybackStateMachineEventsTests.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Stub/HTTPStub.swift
According to the following picture from [Clappr-docs](https://github.com/clappr/clappr-docs/wiki/Architecture), the player should trigger some events when interacting with the playback:
With this PR we want to cover some scenarios of the triggered events, our tests are:
- Expected triggered events: Ready, WillPlay, Stalled, WillPlay, Playing, WillPause, DidPause, WillSeek, DidSeek, WillPlay, Playing, WillStop, WidPause, DidStop
- Expected triggered events: Ready, WillPlay, Stalled, WillPlay, Playing, WillSeek, Stalled, Playing, DidSeek, Stalled, Playing, DidComplete
- Expected triggered events: Ready, WillPause, DidPause, WillPlay, Stalled, WillStop, DidStop
- Expected triggered events: Ready, WillPause, DidPause, WillPlay, Stalled,  WillPause, DidPause, WillStop, DidStop
- Expected …
=> Add tests for the triggered events of the Playback state machine

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackStateMachineEventsTests.swift
There is no `stop` method on `AVPlayer`, to get around this we call `pause` and destroy the `player`. This PR allow us to continue using this approach without trigger `pause` event along the ecosystem.
- We adjust the `AVFoundationPlaybackStateMachineEventsTests` to contemplate this change.
- We don't have an explicit stop call in our sample. Insert this code above in `ViewController.swift` on line 21 and check that we don't trigger pause event before `didStop`. 
```swift
DispatchQueue.main.asyncAfter(deadline: .now()+10) { [weak self] in
self?.player.stop()
}
```
=> Remove pause event when trigger stop

Cartfile.private, Sources/Clappr_iOS/Classes/Plugin/Container/PosterPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift, Tests/Clappr_Tests/PlaybackTests.swift
Do not display media control when video starts.
- Run sample and check if media control is not displayed when video starts;
- Check if media control still working as before when the user touches the screen;
=> Do not display media control when video starts

Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift
* To trigger `stopListening` from the previous Core
* To register externalPlugins in tvOS
=> Fix issues after Core and tvOS Player refactor

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Playback.swift, Sources/Clappr/Classes/Extension/Dictionary+startAt.swift, Tests/Clappr_Tests/Classes/Extensions/Dictionary+startAtTests.swift
To make the option `kStartAt` able to receive the type `Int`.
In `ViewController.swift` line `19` add this code:
```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 10) { [weak self] in
self?.player.configure(options: [kSourceUrl: "http://clappr.io/highline.mp4", kStartAt: 10])
self?.player.play()
}
```
Play a vídeo, wait until the video is reloaded and check if it started in 10s.
=> startAt accepting Integers

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
When we run seek event to any position, didUpdatePosition is triggered before seek event occurs.
To adjust the time when the event is triggered
=> Fix didUpdatePosition trigger moment

Cartfile.resolved, Sources/Clappr/Classes/Base/Playback.swift, Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/TimeIndicator.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Tests/Clappr_Tests/AVFoundationPlaybackStateMachineEventsTests.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/TimeIndicatorTests.swift, Tests/Clappr_Tests/PlaybackTests.swift
Adjust the moment when ready event is triggered to be after AVFoundationPlayback is rendered. 
1 - Comment the line 597 at file AVFoundationPlayback.swift (with this the video will **not** play).
2 - Run Clappr example app;
3 - Check if ready event appears at log.
=> Fix ready event

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Factories/CoreFactory.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Tests/Clappr_Tests/CoreTests.swift, Tests/Clappr_Tests/PlayerTests.swift
Goal
===
Review the Core and Container's lifecycle (creation and destruction).
That should be coherent with the documentation, specified in [clappr-docs](https://github.com/clappr/clappr-docs/wiki/Architecture#loader).
The creation order should be:
**Core -> Core Plugins -> Container -> Container Plugins**
The destruction should happen in the opposite order.
How to Test
===
1. Run `make test`.
2. Check if there are new memory leaks after this change.
3. Test the player manually and check if it works normally.
=> Refactor plugins lifecycle

Tests/Clappr_Tests/AVFoundationPlaybackStateMachineEventsTests.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
Goal
===
Fix the AVFoundationPlayback state machine tests that were flaky by removing the use of Swifter and start using OHTTPStubs instead.
How to Test
===
1. Run `make test`.
=> Fix AVFoundationPlayback flaky tests

Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Layout/MediaControlView.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Layout/MediaControlView.xib, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift
Create a contrast layer to be used as media control background enabling back layer to be used by third-party plugins.
Run example app and make sure that media control background color appear when media control is visible.
=> Create contrast layer in media control

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Options.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Layout/MediaControlView.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift, Tests/Clappr_Tests/CoreTests.swift
Order Media Control plugins based in the kMediaControlPluginsOrder option.
In the Clappr example app `ViewController.swift` add the option before instantiate Player: `options[kMediaControlPluginsOrder] = "TimeIndicator,FullscreenButton"` 
Change the TimeIndicatorPlugin and FullscreenButton to same position, for example left, run the app and check if the order are correct.
**P.S.** Remind that the order of disposing the plugins in media control follow the position so if position is left the first plugin mentioned in the option came to left and if the position was right the first plugin will be displayed at the right.
=> Ordering media control plugins

Sources/Clappr/Classes/Helper/AVURLAssetWithCookiesBuilder.swift, Tests/Clappr_Tests/AVURLAssetWithCookiesTests.swift
**DO NOT MERGE THIS PR**
To not filter which cookies are sent to `AVURLAsset`.
1. Just check if a video plays correctly
=> Do not filter cookies by domain

Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift
Order Media Control plugins based in the kMediaControlPluginsOrder option.
In the Clappr example app `ViewController.swift` add the option before instantiate Player: `options[kMediaControlPluginsOrder] = ["TimeIndicator", "FullscreenButton"]` 
Change the TimeIndicatorPlugin and FullscreenButton to same position, for example left, run the app and check if the order are correct.
**P.S.** Remind that the order of disposing the plugins in media control follow the position so if position is left the first plugin mentioned in the option came to left and if the position was right the first plugin will be displayed at the right.
=> Change the way plugin order option is passed

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Extension/UIView+Ext.swift, Sources/Clappr_iOS/Classes/Base/FullScreen/FullScreenStateHandler.swift, Tests/Clappr_Tests/CoreTests.swift
In order to use the `core.view` frame/bounds to render other plugins, we need to render it before everything else.
=> Fix full screen event trigger after device rotation

Sources/Clappr/Classes/Base/Container.swift, Tests/Clappr_Tests/ContainerTests.swift
- To search plugins by name instead of class type
- Run the test schemes to ensure that everything runs ok
=> Change getPlugin to accept a plugin name instead of a class type

Sources/Clappr_iOS/Classes/Plugin/Base/DoubleTapPlugin.swift, Tests/Clappr_Tests/Classes/Mocks/AVFoundationPlaybackMock.swift, Tests/Clappr_Tests/Classes/Plugins/Core/DoubleTapCorePluginTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/DoubleTapMediaControlPluginTests.swift
- To prevent double tap seek forward when a video is live.
- To make sure we double tap seek when video is live and it has DVR enabled.
- Make sure double tap works as it should
- Run the tests and check if they pass
=> Handle double tap to seek on live videos

Clappr.xcodeproj/project.pbxproj, Sources/Clappr_iOS/Classes/Animation/JumpAnimation.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_iOS/Classes/Plugin/Base/JumpPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/JumpCorePlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/JumpMediaControlPlugin.swift, Tests/Clappr_Tests/Classes/Plugins/Core/JumpCorePluginTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/JumpMediaControlPluginTests.swift
To keep similarity between all Clapprs project, we decided to change _Double Tap Plugin_ to _Jump Plugin_
- Run all Clappr tests
- Check if We forgot to rename something
- Run the application and use the Jump Feature
=> Rename DoubleTap to Jump

Sources/Clappr/Classes/Base/Container.swift, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Factories/ContainerFactory.swift, Sources/Clappr/Classes/Plugin/Container/UIContainerPlugin.swift, Sources/Clappr/Classes/Plugin/Core/UICorePlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/JumpCorePlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/JumpMediaControlPlugin.swift, Tests/Clappr_Tests/Classes/Plugins/Container/UIContainerPluginTests.swift, Tests/Clappr_Tests/ContainerTests.swift, Tests/Clappr_Tests/CoreTests.swift, Tests/Clappr_Tests/PosterPluginTests.swift, Tests/Clappr_Tests/UICorePluginTests.swift
* To handle both `UIPlugin`'s and `Plugin`'s in `Core` and `Container`
* To force `UIPlugin`'s to implement `render()` method
* Make sure that the player still behaves consistently
=> Handle all plugin types in Core and Container

Sources/Clappr/Classes/Enum/InternalEvent.swift, Sources/Clappr_iOS/Classes/Plugin/Base/JumpPlugin.swift, Tests/Clappr_Tests/Classes/Plugins/Core/JumpCorePluginTests.swift
To create new event:
- didTapQuickSeek: triggered when user double tap to seek 10 seconds.
In iOS and tvOS: 
1. Open any vod;
2. Double tap on video
3. Check if didTapQuickSeek event were triggered;
=> Trigger Quickseek event 

Sources/Clappr/Classes/Base/BaseObject.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/TimeIndicator.swift
To fix memory leak issues.
When using `load` or `configure` before, the player ended up using so much memory and processing that the app was freezing.
1. First, change the video that will be loaded. In `DashboardViewController.swift` change the option `kSourceUrl` to:
```
kSourceUrl: "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8"
```
2. In `ViewController.swift` change the `playing` listener to:
```
player.on(Event.playing) { _ in
print("on Play")
DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
self.player.configure(options: self.options)
}
}
```
And `ready` listener to:
```
player.on(Event.ready) { _ in print("on Ready"); self.player.play() }
```
Load a video, grab a coffee, and just wait a couple of minutes. The app should not …
=> Fix memory leak

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
Fix Now Playing to tvOS
1 - run tests
2 - On `AVFoundationNowPlayingService` put a breakpoint at line `16` and check if items property is been set with video information(title, description, date, content identifier, watched time)
=> Fix nowplaying on tvos

Clappr.podspec, Clappr.xcodeproj/project.pbxproj, Tests/Clappr_Tests/Classes/Extensions/String+Ext.swift, Tests/Clappr_Tests/SwiftVersionTests.swift
If swift version is not defined in podspec, cocoapods will select the configured version in application.
This PR puts the version in podspec and test if it matches with version inside .swift-version file. Cocoapods will compile the framework with swift version defined in podspec to avoid application's interference.
1. Change the swift version in Clappr.podspec or in .swift-version file;
2. Run `make test`;
3. The tests should fail;
=> Add swift version in podspec

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Avoid UI freezing when a video is loaded. In `AVFoundationPlayback` there is an audio selection before the first play and this action is freezing the UI. 
We propose to run this routine in another queue with a lower priority.
In our tests with a bad connection, we put a date print mark before and after the execution to compare the time spent. With a higher priority, the audio selection spent 5, 6 seconds to release the UI. With a lower priority, the audio selection spent 1 second.
1 - Put a print mark on line 215:
```
print("Start date -> \(Date())")
```
2 - Put a print mark on line 220:
```
print("End date -> \(Date())")
```  
3 - With `Network Link Conditioner` turned on and with Edge profile, run the sample and try to interact with UI, like pressing back button or tap in the player …
=> Fix UI Freezing

Sources/Clappr/Classes/Base/Container.swift, Sources/Clappr/Classes/Enum/Event.swift, Tests/Clappr_Tests/ContainerTests.swift
To trigger a `didResize` event when player resizes.
1. Subscribe to the container event `didResize`
2. Change the player size (by putting it in fullscreen or resizing the container view)
3. Check that the event is triggered
=> didResize event

Clappr.xcodeproj/project.pbxproj, Example/Clappr_tvOS/ViewController.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Sources/Clappr_tvOS/Classes/Base/TVRemoteHandler.swift, Tests/Clappr_tvOS_Tests/PlayerTests.swift, Tests/Clappr_tvOS_Tests/TVRemoteHandlerTests.swift
`willPlay` and `willPause` playback events are not been triggered on tvOS if users request it using the remote
To trigger `willPlay` and `willPause` events on tvOS player
1 - Check if those events are been triggered
2 - Run tests
=> Fix tvOS playback events

Sources/Clappr/Classes/Base/BaseObject.swift, Tests/Clappr_Tests/BaseObjectTests.swift
- To reduce the "verbosity on listenTo events
- Remove the public keyword within a public extension to remove redundancy
1. On any listenTo events, try to replace it with event: .eventName instead. Is should still work
=> Add a way to listenTo events without having to pass in the event rawValue

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Extension/AVAsset+Ext.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
- To use `loadValuesAsynchronously` from `AVAsset` to get audio and subtitle characteristics, which may block the main thread if you directly access such property.
1. run `make test` and nothing should break
2. If you wish, you can go even further and add a tableView to the player viewController and keep scrolling it while the video is being loaded.
=> Make it possible to load audio sources without blocking the  main thread

Makefile, fastlane/Fastfile, fastlane/README.md
- Allow publishing snapshots from the current branch
- run `make release_snapshot version='0.11.46-snapshot'` and verify that it will create a `pre-release on github`
- You can also try pod install Clappr with the `0.11.46-snapshot` version
=> Release snapshot from a branch

Sources/Clappr/Classes/Base/Playback.swift, Sources/Clappr/Classes/Plugin/Container/ContainerPlugin.swift, Sources/Clappr/Classes/Plugin/Core/CorePlugin.swift, Tests/Clappr_Tests/Classes/Plugins/Container/ContainerPluginTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/CorePluginTests.swift, Tests/Clappr_Tests/PlaybackTests.swift
Whenever a new plugin extending `CorePlugin` or `ContainerPlugin` or a new playback extending `Playback` does not override the `open class var name: String`, the exception will now display the class name like so:
```
Core Plugins should always declare a name. MyNewPluginClass does not.
```
Run `make test`
=> Expose missing plugin name

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Factory/PlaybackFactory.swift, Sources/Clappr/Classes/Plugin/Container/ActiveContainerPlugin.swift, Sources/Clappr/Classes/Plugin/Container/ContainerPlugin.swift, Sources/Clappr/Classes/Plugin/Container/SimpleContainerPlugin.swift, Sources/Clappr/Classes/Plugin/Container/SpinnerPlugin.swift, Sources/Clappr/Classes/Plugin/Container/UIContainerPlugin.swift, Sources/Clappr/Classes/Plugin/Core/ActiveCorePlugin.swift, Sources/Clappr/Classes/Plugin/Core/CorePlugin.swift, Sources/Clappr/Classes/Plugin/Core/SimpleCorePlugin.swift, Sources/Clappr/Classes/Plugin/Core/UICorePlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Base/QuickSeekPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Container/PosterPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/FullscreenButton.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/PlayButton.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Seekbar.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/TimeIndicator.swift, Tests/Clappr_Tests/Classes/Plugins/Container/UIContainerPluginTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlPluginTests.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift, Tests/Clappr_Tests/ContainerTests.swift, Tests/Clappr_Tests/CoreTests.swift, Tests/Clappr_Tests/LoaderTests.swift, Tests/Clappr_Tests/PlayerTests.swift, Tests/Clappr_Tests/UICorePluginTests.swift
The objective of this refactor is push the `bindEvents` up in the hierarchy of plugins so that plugins don't forget to `stopListening` or to re-`bindEvents` when `didChangeActiveContainer` and `didChangeActivePlayback` are triggered.
The main changes are in `ContainerPlugin.swift` and `CorePlugin.swift`. All other changes are so that plugins comply with the new structure.
A secondary benefit is that many plugins now don't need to override the required constructor when the only thing it used to do was to bind events.
1. Run `make test`
2. Test the basic functionality in the example app.
=> Bind events refactor

Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift
- To trigger a `didLoop` event on every video loop
1. On `DashboardViewController.swift`, add a new option: `kLoop: true`
2. On AVFoundationPlayback.swift, place a breakpoint on line 25, within the observer scope
3. Play the video and drag the scrubber to the end of the video
4. You should see the code stopping on your breakpoint
5. You can repeat steps 3 and 4 just to make sure it is always triggering the `didLoop` event.
=> Trigger didLoop event for every video loop

Sources/Clappr_iOS/Classes/Base/FullScreen/FullScreenStateHandler.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Tests/Clappr_Tests/CoreTests.swift, Tests/Clappr_Tests/PlayerTests.swift
Fix a problem where the `userRequest*FullScreen` events were being triggered twice when the option `kFullscreenByApp == false` or not set.
1. Open the example app
2. Play the video
3. Put it in full screen mode and exit.
4. Check that the message `on requestFullscreen`/`on exitFullscreen` only appear once
try variations with the fullscreenByApp true and false, as well as starting the example app already in full screen.
=> Full Screen Events triggered twice

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Tests/Clappr_Tests/CoreTests.swift, Tests/Clappr_Tests/PlayerTests.swift, Tests/Clappr_tvOS_Tests/PlayerTests.swift
- To trigger a `didAttachView` event every time we attach a parentView to it through `attachTo` method.
1. On Player.swift, Create a dummy CorePlugin at the bottom of the file: 
```swift
class AttachPlugin: SimpleCorePlugin {
override class var name: String {
return "AttachPlugin"
}
override open func bindEvents() {
guard let core = core else { return }
listenTo(core, event: Event.didAttachView) { _ in
print("Event.didAttachView").   <---- Breakpoint here! 😄 
}
}
}
```
2. Place a breakpoint on the `print` line of this plugin
3. Run the example project
4. Make sure the app stops at that line
=> Create didAttachView event

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Use newer syntax when adding key-value observer to player properties.
Everything is pretty much covered by unit tests. So just `make test`
=> Refactors AvFoundationPlayback to use newer kvo syntax

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Tests/Clappr_Tests/AVFoundationPlaybackTests.swift, Tests/Clappr_Tests/PlayerTests.swift, Tests/Clappr_tvOS_Tests/PlayerTests.swift
To trigger `.willLoadSOurce` from core whenever `player.configure` or player.load is called. This should let plugins prepare for fresh options if they need to.
=> Trigger willLoadSource from core when player.configure or load are called

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Container.swift, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Enum/InternalEvent.swift, Sources/Clappr_iOS/Classes/Base/OrientationObserver.swift, Sources/Clappr_iOS/Classes/Plugin/Base/QuickSeekPlugin.swift, Tests/Clappr_Tests/Classes/Plugins/Core/QuickSeekCorePluginTests.swift
- To trigger a `didChangeScreenOrientation` event every orientation change.
- To trigger a `didDoubleTouchMediaControl` event every consecutive double tap on screen.
1. On `ViewController.swift#52` add this piece of code:
```swift
player.on(Event.didChangeScreenOrientation) { _ in
print("on didChangeScreenOrientation")
}
```
2. On `Player.swift#100` add the event to trigger on player layer:
```swift
core?.activeContainer?.on(Event.didChangeScreenOrientation.rawValue) { [weak self] (info: EventUserInfo) in self?.trigger(Event.didChangeScreenOrientation.rawValue, userInfo: info) }
```
3. Check the console log and ensure that `on didChangeScreenOrientation` was printed
1. On `ViewController.swift#52` add this piece of code:
```swift
player.on(Event.didDoubleTouchMediaControl) { _ in …
```
=> Create didChangeScreenOrientation and didDoubleTouchMediaControl events 

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Container.swift, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/SharedData.swift, Tests/Clappr_Tests/ContainerTests.swift, Tests/Clappr_Tests/CoreTests.swift
- To add to Core the ability to store shared data across the player lifecycle
1. Store anything you want on `core.sharedData` and try to retrieve it
2. Run the tests (they execute the step 1).
=> Add sharedData to core

Sources/Clappr/Classes/Base/Container.swift, Tests/Clappr_Tests/ContainerTests.swift
- Add view bound size on didResize event. 
- Run tests
- Listen the event didResize, put the player in fullscreen and ensure that userInfo event has the values from new view size.
=> Add view bounds size on didResize event param

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Tests/Clappr_Tests/AVFoundationPlaybackStateMachineEventsTests.swift
Willpause event was being triggered in `Player` for tvOS, but it was not working on a real device.
We had to change where the event is triggered. The event is being triggered in `AVFoundationPlayback`. 
Run tvOS sample and check if `on willPause` is printed when the video is paused.
=> Change way to trigger willPause event in tvOS

Sources/Clappr/Classes/Base/Core.swift, Tests/Clappr_Tests/Classes/Plugins/Core/MediaControl/MediaControlTests.swift, Tests/Clappr_Tests/CoreTests.swift
- We found that the order of which the plugins are rendered, can cause an issue with positioning.
Therefore, we have to make sure we render the mediaControl Elements after everything is being positioned.
- Run the test suite, because there's a test that was implemented just to make sure we don't invert the rendering order: `Core -> MediaControl`
=> Render plugins order

Sources/Clappr/Classes/Base/Factories/ContainerFactory.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_tvOS/Classes/Base/Player.swift, Tests/Clappr_Tests/Classes/Plugin/Container/ContainerTests.swift, Tests/Clappr_Tests/Classes/Plugin/Container/PosterPluginTests.swift, Tests/Clappr_tvOS_Tests/PlayerTests.swift
Fix the event `willLoadSource` to trigger on player init.
Put a breakpoint to get the `Player.init` and check if `core.load` is called and ensure that `willLoadSource` is triggered.
=> Player load core

Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackStateMachineEventsTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
Trigger `assetAvailable` event when `AVURLAsset` is ready. 
1.  Add this code on ViewController.swift
```swift
player.on(Event.assetReady) { _ in
print("on assetReady")
}
```
2. Add `Event.assetReady.rawValue` on `Player.swift#81`
=> Asset available event

Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Layout/MediaControlView.xib, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/MediaControlTests.swift
- Now that we have a way to add a bottom placeholder to mediaControl, we want to apply this constraint to the `none` panel as well. This PR is simply changing the bottom constraint of this panel to use the StackView bottom constraint.
- Run the tests and nonthing should fail as this is a simple constraint replacement and a simple change on the way we pass the placeholder height
=> MediaControl none panel bottom constraint

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Enum/InternalEvent.swift, Sources/Clappr/Classes/Extension/PanGesture+Ext.swift, Sources/Clappr/Classes/Extension/UIView+Ext.swift, Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/BottomDrawerPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/DrawerPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/Drawer/BottomDrawerPluginTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/Drawer/DrawerPluginTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/MediaControlTests.swift
We are introducing the BottomDrawerPlugin structure, that allows customizing `DrawerPlugin` with a bottom behavior. With this, it's possible to create a plugin from the bottom screen.
1 - Add this code on BottomDrawerPlugin.swift#127 
```swift
}
return 32.0
}
super.render()
}
}
```
2 - Add `CustomBottomDrawerPlugin.self` on Player.swift#208
3 - Interact with the red view by tap and drag gesture
=> Bottom drawer plugin

Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/BottomDrawerPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/MediaControlTests.swift
When we have subviews in a plugin of type BottomDrawerPlugin the events of click dont work because of the gestures recognizers. We just set the `cancelsTouchesInView` to false to make this work. And make minor changes in `MediaControl` removing the flag `showOnDrawerHide`and validating if the media control can show when drawer hides by the `PlaybackState`.
1 - Add this code on BottomDrawerPlugin.swift#127 
```swift
}
return 32.0
}
super.render()
let button = UIButton()
button.backgroundColor = .gray
button.setTitle("Click me", for: .normal)
button.addTarget(self, action: #selector(cliked), for: …
```
=> Fix events of click in subview of drawer plugin

Example/Clappr/ViewController.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Tests/Clappr_Tests/Classes/Base/PlayerTests.swift
This PR fixes issue #319 
To propagate media control events on the player, so that external plugins and such can listen to the `willShowMediaControl`, `didShowMediaControl`, `willHideMediaControl` and `didHideMediaControl` events.
1 - Interact with the player and check if media control events are being printed on the console as they're triggered.
2 - Run tests.
=> Propagates media control events on player

Sources/Clappr/Classes/Enum/Event.swift, Sources/Clappr/Classes/Plugin/Core/OverlayPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Base/QuickSeekPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/DrawerPlugin.swift, Tests/Clappr_Tests/Classes/Plugin/Core/OverlayPluginTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/QuickSeekCorePluginTests.swift
- To prevent quick seek to overpass the overlay plugins while presenting them
1. Create a dummy DrawerPlugin:
```swift
}
return 32.0
}
super.render()
}
}
```
and add it to the list of built in plugins `(Player.swift file)`
2. Run the sample app
3. Tap on the red area to present the drawer plugin
4. Try to double tap the screen like if you were to quick seek forward or backward
5. Nothing should happen
=> Prevent quick-seek on overlay plugins

Sources/Clappr/Classes/Base/Playback.swift, Sources/Clappr/Classes/Extension/AVFoundationPlayback+DVR.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
As we need to know what time is the current live date, we are adding a property that is meant to expose the current live time of a given video.
1. Since this property is not used in the current player sample app, please run the tests and see that nothing breaks.
=> Add the current live date property to playback

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackStateMachineEventsTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
To trigger state events right after some user action, such as seek, play and pause.
1. Run the sample app
1. Pause the video
1. Seek to any position
1. Check if there was a `on Pause` in the console right after the `on didSeek`.
1. Play the video
1. Seek to any position
1. Check if there was a `on Play` in the console right after the `on didSeek`.
1. Force the player to buffer (This can be done by simulating a poor connection)
1. Seek to any position
1. Check if there was a `on Stalling` in the console right after the `on didSeek`.
*We've commented a test because the fix to make it succeed will come in another PR.*
=> Trigger events to identify states

Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/QuickSeekMediaControlPlugin.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/QuickSeekMediaControlPluginTests.swift
Goal
-
To make `QuickSeek` work when the media control is visible and there are `Overlay` plugins.
How To Test
-
1. Play a video
1. Make the media control visible
1. Double tap on the sides
1. The quick seek should take effect
=> Fix QuickSeek when media control is visible

Clappr.xcodeproj/project.pbxproj, Example/Clappr_tvOS/ViewController.swift, Sources/Clappr/Classes/Base/MediaOption.swift, Sources/Clappr/Classes/Factory/MediaOptionFactory.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackMediaSelectionTests.swift, Tests/Clappr_Tests/Classes/Stubs/CoreStub.swift
Fix default subtitle when `options[kDefaultSubtitle] = "off"` is passed.
You can modify the DashboardViewController.swift#19 to:
```swift
let options: Options = [
kSourceUrl: "http://sample.vodobox.com/planete_interdite/planete_interdite_alternate.m3u8",
kPosterUrl: "http://clappr.io/poster.png",
kDefaultSubtitle: "off",
kFullscreen: switchFullscreen.isOn,
kFullscreenByApp: switchFullscreenControledByApp.isOn
]
```
With this, the subtitle should not appear on video.
```swift
let options: Options = [
kSourceUrl: "http://sample.vodobox.com/planete_interdite/planete_interdite_alternate.m3u8",
kPosterUrl: "http://clappr.io/poster.png",
kDefaultSubtitle: "fre",
kFullscreen: switchFullscreen.isOn,
kFullscreenByApp: switchFullscreenControledByApp.isOn
]
```
With this, the subtitle should appear …
=> Fix default subtitle

Sources/Clappr_iOS/Classes/Base/Player.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
Allow for the iOS Player to be muted. This was already possible on the tvOS target, this PR uses the same strategy on iOS and add some tests.
- Run the test suite
=> Allow the player to be muted on iOS

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Container.swift, Sources/Clappr/Classes/Plugin/Container/SpinnerPlugin.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/PlayButton.swift, Tests/Clappr_Tests/Classes/Mocks/AVFoundationPlaybackMock.swift, Tests/Clappr_Tests/Classes/Mocks/PlayerItemMock.swift, Tests/Clappr_Tests/Classes/Mocks/PlayerMock.swift, Tests/Clappr_Tests/Classes/Plugin/Container/ContainerTests.swift, Tests/Clappr_Tests/Classes/Plugin/Container/SpinnerPluginTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/PlayButtonTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackStopActionTests.swift, Tests/Clappr_Tests/Classes/Stubs/ContainerStub.swift
- Create reload flow on Container
- Clear objects when stop is call
- Expose function on Playbutton
- Fix spinner visibility when pause and stop events is triggered
- Try to call reload function with other configurations, like: 
On `Player.swift#150`
```swift
open func reload(sourceUrl: String) {
core?.activeContainer?.reload(source: sourceUrl)
}
```
On `ViewController.swift#101`
```swift
@IBAction func recreatePlayer(_ sender: Any) {
player.destroy()
player = nil
createPlayer()
let sourceUrl = "https://www.radiantmediaplayer.com/media/bbb-360p.mp4"
player.reload(sourceUrl: sourceUrl)
player.play()
}
```
- The other goals were covered by unit tests. You can check there
=> Reload Container

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Change `AVAudioSession.category` to `.playback`to fix the behavior of not playing the video audio when the silent mode is activated.
1 - Run test suite
2 - Run Clappr_Exemple target on a device, play a video, switch silent mode, and see the audio playing with no problems.
=> Change audio session category to .playback

Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/PlayButton.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/PlayButtonTests.swift
Add `didStop` event listener to show `PlayButton` with a `play` icon.
- On `ViewController.swift#100`
```swift
@IBAction func recreatePlayer(_ sender: Any) {
player.stop()
}
```
- Run the sample and play a video
- Click on `Recreate Player` button and check if the play button will show on the player' screen.
=> Add didStop listener on PlayButton

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Mocks/PlayerMock.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackStopActionTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
- Reset properties on `AVFoundationPlayback.destroy()`
- Introduce `AVFoundationPlaybackStopActionTests`
- Create default error on `AVFoundationPlayback.onFailedToPlayToEndTime`
- Minor code styles refactor
=> Clear objects on AVFoundationPlayback.destroy()

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Options.swift, Sources/Clappr/Classes/Enum/InternalEvent.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Tests/Clappr_Tests/Classes/Base/PlayerTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift
Introduce request destroy player behavior when user request exit full screen on Core
on `Example/Clappr`
`Player.swift#272`
```swift
open func exitFullscreen() {
core?.trigger(InternalEvent.userRequestExitFullscreen.rawValue)
}
```
`ViewController.swift#21`
```swift
player.on(Event.playing) { [weak self] _ in
self?.exitFullscreen()
print("on Play")
}
```
`ViewController.swift#60`
```swift
player.on(Event.didDestroy) { _ in
print("on didDestroy")
}
```
`ViewController.swift#65`
```swift
private func exitFullscreen() {
DispatchQueue.main.asyncAfter(deadline: .now()+5) { [weak self] in
self?.player.exitFullscreen()
}
}
```
5 seconds after the first `playing` event, the player should destroy and the console should have the message `on didDestroy`
=> Request Destroy Player

Sources/Clappr/Classes/Base/BaseObject.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControlElement.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/MediaControlTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/Seekbar/Views/SeekbarViewTests.swift
Goal
---
To refactor `MediaControl` code and adjust its behaviour.
How to Test
---
1. Interact with the Media Control and check if it respects the following rules:
- Every transition is animated, including showing/hiding drawers
- It appears at the beggining of the video after the first play
- Has a inactivity time of 3 seconds
- It automatically disappears after 0.3 seconds after a user interaction when `playing`
- It does not automatically disappears after user interaction when `paused` / `idle`
2. Run tests
=> Refactor media control

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Font/Alignment.swift, Sources/Clappr/Classes/Base/Font/Direction.swift, Sources/Clappr/Classes/Base/Font/EdgeStyle.swift, Sources/Clappr/Classes/Base/Font/Font.swift, Sources/Clappr/Classes/Base/Font/TextStyle.swift, Sources/Clappr/Classes/Base/Playback.swift, Sources/Clappr/Classes/Extension/AVPlayerItem+Style.swift, Sources/Clappr/Classes/Extension/UIColor+ARGB.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Base/FontTests.swift, Tests/Clappr_Tests/Classes/Mocks/AVFoundationPlaybackMock.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
Introduce player capability to change the subtitle style.
Create an abstraction from `AVTextStyleRules` to use a non-verbose code
Change the `options` on `DashboardViewController.swift#19`
```swift
let options: Options = [
kSourceUrl: "http://sample.vodobox.com/planete_interdite/planete_interdite_alternate.m3u8",
kPosterUrl: "http://clappr.io/poster.png",
kDefaultSubtitle: "eng",
kFullscreen: switchFullscreen.isOn,
kFullscreenByApp: switchFullscreenControledByApp.isOn
]
```
Change the `selectDefaultMediaOptionIfNeeded` function  on `AVFoundationPlayback.swift#650`
```swift
func selectDefaultMediaOptionIfNeeded() {
selectDefaultAudioIfNeeded()
changeSubtitle(style: [ 
.font(.fantasy), 
.bold, 
.background(.blue) 
])
selectDefaultSubtitleIfNeeded()
}
```
Run `Clappr_Example`
Run …
=> Subtitle Style

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Font/TextStyle.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Base/FontTests.swift, Tests/Clappr_Tests/Classes/Mocks/PlayerItemMock.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackMediaSelectionTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackSubtitleTests.swift
Introduce the following capabilities for playback subtitles:
1. Change the subtitle size;
2. Change the subtitle container size;
3. Automatically hide subtitles when the player was resized to small sizes.
On `DashboardViewController.swift#19` change the code:
```swift
let options: Options = [
kSourceUrl: "http://sample.vodobox.com/planete_interdite/planete_interdite_alternate.m3u8",
kPosterUrl: "http://clappr.io/poster.png",
kFullscreen: switchFullscreen.isOn,
kFullscreenByApp: switchFullscreenControledByApp.isOn,
kDefaultSubtitle: "fre"
]
```
On `AVFoundationPlayback.swift#65` change the code:
```swift
private let minSizeToShowSubtitle = CGSize(width: 376, height: 212)
```
- Run the Clappr_Example
- On portrait, the subtitle should not appear
- Put the app on fullscreen mode
- The …
=> Subtitle style based on Player size

Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/BottomDrawerPlugin.swift, Tests/Clappr_Tests/Classes/Plugin/Core/Drawer/BottomDrawerPluginTests.swift
Fix gesture handler on drag bottom drawer when showing and hiding 
1. Run unit tests.
2. Interact with drawer
On `ViewController.swift` insert:
`Line #94`
```swift
Player.register(plugins: [CustomBottomDrawerPlugin.self])
```
`Line #110`
```swift
}
return 32.0
}
super.render()
}
}
```
=> Fix bottom drawer gesture handler

Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/BottomDrawerPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/DrawerPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/QuickSeekMediaControlPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/QuickSeekCorePlugin.swift, Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/Drawer/BottomDrawerPluginTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/Drawer/DrawerPluginTests.swift
Fixes the drawer anchors when exiting fullscreen 
On `ViewController.swift` insert:
`Line #94`
```swift
Player.register(plugins: [CustomBottomDrawerPlugin.self])
```
`Line #110`
```swift
}
return 32.0
}
super.render()
}
}
```
1 - Portrait Mode
- Run the Clappr_Example and verify if the CustomDrawer is showing and interactable
- Click on Fullscreen button
- The drawer must be resized with the new screen size and interactable
- Click on Fullscreen button
- The drawer must be resized with the new screen size and interactable in the portrait mode
2 - Landscape Mode
- Run the …
=> Fix Drawer Exit Fullscreen

Sources/Clappr/Classes/Base/Playback.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Base/PlaybackTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackQualityMetricsTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackStopActionTests.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
Stop playback before destroying the player in order to maintain state integrity.
- Run the automated tests
=> Stop Playback before destroying it

Sources/Clappr/Classes/Base/Container.swift, Sources/Clappr/Classes/Base/Core.swift, Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift
Fix the problem introduced on #396, where the `Container` view was still being added to the Core view, which should only happen on tvOS.
1. Run all automated tests
=> Fix Container view hierarchy

Sources/Clappr/Classes/Base/Options.swift, Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Allow the client application to disable external playback, such as AirPlay.
⚠️  As there's no AirPlay support on the simulator, to test this you'll need a device to run the example application and another one to use as the AirPlay destination, such as an Apple TV.
1. Run the Example app
2. Play the video
3. Open the Control Center
4. Connect to the Apple TV
5. Video and audio should play normally on the TV
1. On the example app, add the following line at ViewController.swift:94
```swift
options[kDisableExternalPlayback] = true
```
1. Build and run the Example app
2. Play the video
3. Open the Control Center
4. Connect to the Apple TV
5. Video and audio should play locally
=> Disable external playback

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Layers/LayerComposer.swift, Sources/Clappr/Classes/Base/Layers/MediaControlLayer.swift, Tests/Clappr_Tests/Classes/Base/Layers/LayerComposerTests.swift, Tests/Clappr_Tests/Classes/Base/Layers/MediaControlLayerTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/QuickSeekMediaControlPluginTests.swift
Continue the implementation of the visual layers abstraction by adding Media Control layer.
1. Add the following snippet to LayerComposer.swift#19
```swift
mediaControlLayer.backgroundColor = .yellow
```
2. Run the Clappr_Example project
3. Enable view hierarchy debugger
4. You should be able to see the new layer
=> Create MediaControl layer

Sources/Clappr/Classes/Base/Layers/ContainerLayer.swift, Sources/Clappr/Classes/Base/Layers/PlaybackLayer.swift, Tests/Clappr_Tests/Classes/Base/Layers/ContainerLayerTests.swift, Tests/Clappr_Tests/Classes/Base/Layers/PlaybackLayerTests.swift
Change the method `attach` view on `LayerComposer` to update the layout if need on `SuperView` .
1. Run the Clappr_Example project
=> Change layer composer attach to update layout on SuperView

Sources/Clappr_tvOS/Classes/Base/Player.swift
Enable register of plugins to the tvOS player
1. Add the following snippet to ViewController.swift#67 (Clappr_tvOS)
```swift
class PlaybackTypePlugin: SimpleCorePlugin {
override class var name: String { "PlaybackTypePlugin" }
override func bindEvents() {
guard let playback = core?.activePlayback else { return }
listenTo(playback, event: .assetReady) { _ in
switch playback.playbackType {
case .live:
print("Playback Type: Live")
case .vod:
print("Playback Type: VoD")
default:
print("Playback Type: Unknown")
}
}
}
}
```
2. Add the following snippet to ViewController.swift#17  (Clappr_tvOS)
```swift
Player.register(plugins: [PlaybackTypePlugin.self])
```
3. Run the Clappr_tvS=OS_Example project
4. Active Console
5. You should be able to see "Playback Type: VoD" on the console
=> Register plugins (tvOS)

Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/BottomDrawerPlugin.swift
Goal
---
To close the drawer plugin only when it's open when changing screen orientation, preventing any unexpected behavior in plugins that listen to drawer events.
How To Test
---
1. Add this snippet to `ViewController.swift#94`, before instantiating the Player:
```swift
Player.register(plugins: [CustomBottomDrawerPlugin.self])
```
1. Add this snippet to `ViewController.swift#110`, after the ViewController class definition: 
```swift
}
return 32.0
}
super.render()
}
}
```
1. Run `Clappr_Example`
1. Uncheck the `Fullscreen controlled by app` switch
1. Tap `Start video`
1. …
=> Close bottom drawer plugin only if it's open on orientation change

Clappr.xcodeproj/project.pbxproj, Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Layers/LayerComposer.swift, Sources/Clappr/Classes/Base/Layers/OverlayLayer.swift, Tests/Clappr_Tests/Classes/Base/Layers/ContainerLayerTests.swift, Tests/Clappr_Tests/Classes/Base/Layers/LayerComposerTests.swift, Tests/Clappr_Tests/Classes/Base/Layers/LayerTests.swift, Tests/Clappr_Tests/Classes/Base/Layers/MediaControlLayerTests.swift, Tests/Clappr_Tests/Classes/Base/Layers/OverlayLayerTests.swift, Tests/Clappr_Tests/Classes/Base/Layers/PlaybackLayerTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/OverlayPluginTests.swift
To have a layer that controls the views of overlay plugins.
1. Add the following snippet to LayerComposer.swift#20
```swift
overlayLayer.backgroundColor = .red
```
1. Run the example
1. Enable view hierarchy debugger
1. You should see the OverlayLayer view with a red background as shown in the `Screenshot` section.
1. Run the example
1. Double tap on both sides
1. Make sure the Quick Seek feature works as expected.
1. Run the example
1. Add the following snippet in `ViewController` as a plugin:
```swift
}
return 32.0
}
private let internalView = UIView()
super.render()
Logger.setLevel(.debug)
let …
```
=> Create the Overlay layer

Sources/Clappr_iOS/Classes/Base/Player.swift
Goal
---
Expose access control for `Core` property on Player to allow external frameworks to be able to access and listen to `Core` events on the correct context layer.
How To Test
---
Classes on external frameworks that inherited from `Player.swift` should be able to access the property `core` only as a getter.
=> Changes the access control on core

Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/Layout/MediaControlView.xib
Goal
---
Fix a problem where TimeIndicator would show with a black background in Xcode12 / iOS 14.
How to Test
---
1. Run `Clappr_Example`
1. Make sure that the `TimeIndicator` background is transparent.
_To reproduce the bug, just go to a previous commit / branch and go through the above mentioned steps._
=> Fix TimeIndicator background on Xcode 12 / iOS 14

Sources/Clappr/Classes/Plugin/Container/SpinnerPlugin.swift, Tests/Clappr_Tests/Classes/Plugin/Container/SpinnerPluginTests.swift
The `SpinnerPlugin` is currently a UIContainerPlugin and this plugin should be adjusted for its the correct layer, which is the OverlayPlugin.
1. Run the example
1. Enable view hierarchy debugger
1. You should see the SpinnerPlugin in the OverlayLayer hierarchy.
=> Convert SpinnerPlugin to OverlayPlugin

Sources/Clappr_iOS/Classes/Plugin/Container/PosterPlugin.swift, Tests/Clappr_Tests/Classes/Plugin/Container/PosterPluginTests.swift
The `PosterPlugin` is currently a UIContainerPlugin and this plugin should be adjusted for its the correct layer, which is the OverlayPlugin.
1. Run the example
1. Enable view hierarchy debugger
1. You should see the PosterPlugin in the OverlayLayer hierarchy.
=> Convert PosterPlugin to OverlayPlugin

Sources/Clappr/Classes/Base/Core.swift, Sources/Clappr/Classes/Base/Layers/LayerComposer.swift, Sources/Clappr_iOS/Classes/Base/Player.swift, Sources/Clappr_iOS/Classes/Plugin/Container/PosterPlugin.swift, Sources/Clappr_iOS/Classes/Plugin/Core/MediaControl/MediaControl.swift, Sources/Clappr_iOS/Classes/Plugin/Core/QuickSeekCorePlugin.swift, Tests/Clappr_Tests/Classes/Base/Layers/LayerComposerTests.swift, Tests/Clappr_Tests/Classes/Base/PlayerTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift, Tests/Clappr_Tests/Classes/Plugin/Core/QuickSeekCorePluginTests.swift
Introduce `Chromeless` mode to remove user interaction and visual elements on iOS.
Scenario 1
1 - Add the code on ViewController.swift#18:
```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 5) {
self.player.chromelessMode = true
}
DispatchQueue.main.asyncAfter(deadline: .now() + 10) {
self.player.chromelessMode = false
}
```
- Run the playground
- At 00:05s the interactions with playback will be disabled and the visual elements will be hide.
- At 00:10s the interactions with playback will be enabled.
Scenario 2
- Add the code on ViewController.swift#18:
```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 5) {
self.player.configure(options: [kChromeless: true])
}
DispatchQueue.main.asyncAfter(deadline: .now() + 10) {
self.player.configure(options: [kChromeless: false])
}
```
- …
=> Chromeless mode for iOS

Sources/Clappr_iOS/Classes/Plugin/Container/PosterPlugin.swift, Tests/Clappr_UITests/PlaybackTests.swift, Tests/Clappr_UITests/Player/PlayerViewElements.swift, Tests/Clappr_UITests/Player/PlayerViewInteractor.swift
The PosterPlugin has a playButton that we use to play the video on the playback tests. 
Since we change the poster plugin to another layer we need to update this test to reflect this change. 
- Run UI Tests for Clappr
=> Adjust PlaybackTest to reflect new PosterPlugin layer

Sources/Clappr/Classes/Base/Playback.swift
Change `minDvrSize` visibility to open to keep consistency with other properties related to DVR.
1 . Run all automated tests
=> Change minDvrSize visibility to open

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
Adjust seek to live position on iOS 14 to use `seekableTimeRanges` instead of using the `infinity` to seek. 
1 . Run all automated tests
=> Adjust seek to live position on iOS 14

Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift, Tests/Clappr_Tests/Classes/Plugin/Playback/AVFoundationPlaybackTests.swift
This fixes a bug when the `AVFoundationPlayback` is created without an asset and we add a new item on the player later in time the `AVURLAsset` and the `AVPlayerItemInfo` are not being set correctly and the event `.ready` is not being triggered. 
Run unit tests
=> Fix Call update asset if needed when player current item changes

Sources/Clappr_iOS/Classes/Animation/SeekBubble/SeekBubble.swift
This fixes a bug when the `SeekBubble` is called after parent view is dismissed.
Try seek to left or right and dismiss Player (fast way)
=> Fix crash on SeekBubble 
